# docker-compose up
app:
  image: ibmcom/swift-ubuntu:3.1.1
  volumes:
    - .:/root/cf-deployment-tracker-client-swift
  command: bash -c "cd /root/cf-deployment-tracker-client-swift && swift package clean && swift build && swift test"
